#!/bin/sh

declare -a LIST_OF_WINDOW_TITLES_THAT_PREVENT_LOCKING=(
    "YouTube"
)

is_fullscreen() {
    xprop -id $1 | awk -F '=' '$1 ~ /_NET_WM_STATE\(ATOM\)/ { for (i=2; i<=3; i++) if ($i ~ /FULLSCREEN/) exit 0; exit 1 }'
    return $?
}

should_lock() {
    id=$(xprop -root | awk '$1 ~ /_NET_ACTIVE_WINDOW/ { print $5 }')
    title=$(xprop -id $id | awk -F '=' '$1 ~ /_NET_WM_NAME\(UTF8_STRING\)/ { print $2 }')
    if is_fullscreen $id; then
      return 1
    fi
    for i in "${LIST_OF_WINDOW_TITLES_THAT_PREVENT_LOCKING[@]}"; do
      if [[ $title =~ $i ]]; then
          return 1
      fi
    done
}

if should_lock; then
    betterlockscreen --lock blur dim
fi

